# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

pod “FBSDKCoreKit";
pod "FBSDKLoginKit";
pod "FBSDKShareKit";
pod "FBSDKMessengerShareKit";
pod 'Alamofire', '~> 3.3'
pod 'MBProgressHUD', '~> 0.9'
pod 'AFDropdownNotification', '~> 1.0'
pod 'CrittercismSDK'

target 'ITP344Homework' do

end

target 'ITP344HomeworkTests' do

end

target 'ITP344HomeworkUITests' do

end

